name: 'Check PR Title'

on:
  pull_request:
    types: 
      - opened
      - edited 
      - reopened
      - synchronize
    
    branches:
      - main

jobs: 
  commitlint:
    name: 'Check PR title' 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

        with:
          node-version: 18.x
          cache: npm
 
      - name: Run commitlint
        run: |    
          npm install @commitlint/cli @commitlint/config-conventional
          echo '${{ github.event.pull_request.title }}' | npx @commitlint/cli  
