name: Verify PR

on:
  pull_request:
    branches: [ "master" ]

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 12.14.1
      uses: actions/setup-node@v3
      with:
        node-version: 12.14.1
        cache: 'npm'
    - run: npm ci
    - run: npm run audit:ci
    - run: npm run build
    - run: npm run lint
    - run: npm test
